// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestingHosting.Platform.Persistence;

#nullable disable

namespace TestingHosting.Platform.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20261005154346_StudentImportJournal")]
    partial class StudentImportJournal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestingHosting.Platform.IdentityAccess.TeacherUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("TeacherUsers", "platform");
                });

            modelBuilder.Entity("TestingHosting.Platform.IdentityAccess.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Workspaces", "platform");
                });

            modelBuilder.Entity("TestingHosting.Platform.IdentityAccess.WorkspaceMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TeacherUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherUserId");

                    b.HasIndex("WorkspaceId", "TeacherUserId")
                        .IsUnique();

                    b.ToTable("WorkspaceMemberships", "platform");
                });

            modelBuilder.Entity("TestingHosting.Platform.Persistence.StudentImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedStudentCount")
                        .HasColumnType("integer");

                    b.Property<string>("ProgramMapDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<int>("RowCount")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("UnchangedStudentCount")
                        .HasColumnType("integer");

                    b.Property<string>("WorkbookDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Source", "WorkbookDigest", "ProgramMapDigest")
                        .IsUnique();

                    b.ToTable("StudentImportBatches", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_StudentImportBatches_Counts", "\"RowCount\" >= 0 AND \"CreatedStudentCount\" >= 0 AND \"UnchangedStudentCount\" >= 0 AND \"CreatedStudentCount\" + \"UnchangedStudentCount\" = \"RowCount\"");

                            t.HasCheckConstraint("CK_StudentImportBatches_ProgramMapDigest_Length", "length(\"ProgramMapDigest\") = 64");

                            t.HasCheckConstraint("CK_StudentImportBatches_WorkbookDigest_Length", "length(\"WorkbookDigest\") = 64");
                        });
                });

            modelBuilder.Entity("TestingHosting.Platform.Students.LearningProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Code")
                        .IsUnique();

                    b.ToTable("Programs", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_Programs_Code_NotEmpty", "length(\"Code\") > 0");
                        });
                });

            modelBuilder.Entity("TestingHosting.Platform.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Students", "platform");
                });

            modelBuilder.Entity("TestingHosting.Platform.Students.WorkspaceStudentMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImportExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ImportSource")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("WorkspaceId", "CodeHash")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "ProgramId");

                    b.HasIndex("WorkspaceId", "StudentId")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "ImportSource", "ImportExternalId")
                        .IsUnique()
                        .HasFilter("\"ImportSource\" IS NOT NULL AND \"ImportExternalId\" IS NOT NULL");

                    b.ToTable("WorkspaceStudentMemberships", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_WorkspaceStudentMemberships_CodeHash_Length", "octet_length(\"CodeHash\") = 32");

                            t.HasCheckConstraint("CK_WorkspaceStudentMemberships_ImportIdentity", "(\"ImportSource\" IS NULL) = (\"ImportExternalId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("TestingHosting.Platform.IdentityAccess.WorkspaceMembership", b =>
                {
                    b.HasOne("TestingHosting.Platform.IdentityAccess.TeacherUser", "TeacherUser")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("TeacherUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingHosting.Platform.IdentityAccess.Workspace", "Workspace")
                        .WithMany("TeacherMemberships")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeacherUser");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TestingHosting.Platform.Persistence.StudentImportBatch", b =>
                {
                    b.HasOne("TestingHosting.Platform.IdentityAccess.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TestingHosting.Platform.Students.LearningProgram", b =>
                {
                    b.HasOne("TestingHosting.Platform.IdentityAccess.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TestingHosting.Platform.Students.WorkspaceStudentMembership", b =>
                {
                    b.HasOne("TestingHosting.Platform.Students.Student", "Student")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingHosting.Platform.IdentityAccess.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingHosting.Platform.Students.LearningProgram", "Program")
                        .WithMany("StudentMemberships")
                        .HasForeignKey("WorkspaceId", "ProgramId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("Student");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TestingHosting.Platform.IdentityAccess.TeacherUser", b =>
                {
                    b.Navigation("WorkspaceMemberships");
                });

            modelBuilder.Entity("TestingHosting.Platform.IdentityAccess.Workspace", b =>
                {
                    b.Navigation("TeacherMemberships");
                });

            modelBuilder.Entity("TestingHosting.Platform.Students.LearningProgram", b =>
                {
                    b.Navigation("StudentMemberships");
                });

            modelBuilder.Entity("TestingHosting.Platform.Students.Student", b =>
                {
                    b.Navigation("WorkspaceMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
