// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestingHosting.Platform.Persistence;

#nullable disable

namespace TestingHosting.Platform.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20261006220000_HomeworkModelSnapshotSync")]
    partial class HomeworkModelSnapshotSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestingHosting.Platform.Homework.HomeworkAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignmentRecordId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("CatalogItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeadlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HomeworkEventId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("HomeworkId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LegacyLessonId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("ScorePercent")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TaskNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("WorkspaceId", "Id");

                    b.HasAlternateKey("WorkspaceId", "Id", "MembershipId", "StudentId", "ProgramId")
                        .HasName("AK_HomeworkAssignments_SubmissionIdentity");

                    b.HasIndex("WorkspaceId", "AssignmentRecordId")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "ProgramId");

                    b.HasIndex("WorkspaceId", "CatalogItemId", "ProgramId", "HomeworkId");

                    b.HasIndex("WorkspaceId", "MembershipId", "StudentId", "ProgramId");

                    b.HasIndex("WorkspaceId", "MembershipId", "ProgramId", "HomeworkId", "AssignedAt");

                    b.ToTable("HomeworkAssignments", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_HomeworkAssignments_Deadline", "\"DeadlineAt\" > \"AssignedAt\"");

                            t.HasCheckConstraint("CK_HomeworkAssignments_RequiredStrings", "length(\"AssignmentRecordId\") > 0 AND length(\"HomeworkId\") > 0 AND length(\"Name\") > 0 AND length(\"Url\") > 0 AND length(\"Status\") > 0 AND length(\"SchemaVersion\") > 0");

                            t.HasCheckConstraint("CK_HomeworkAssignments_TaskScore", "\"TaskNumber\" BETWEEN 1 AND 1000 AND (\"ScorePercent\" IS NULL OR \"ScorePercent\" BETWEEN 0 AND 100)");
                        });
                });

            modelBuilder.Entity("TestingHosting.Platform.Homework.HomeworkCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HomeworkId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("TaskNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("WorkspaceId", "Id");

                    b.HasAlternateKey("WorkspaceId", "Id", "ProgramId", "HomeworkId")
                        .HasName("AK_HomeworkCatalog_Identity");

                    b.HasIndex("WorkspaceId", "ProgramId", "HomeworkId")
                        .IsUnique();

                    b.ToTable("HomeworkCatalogItems", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_HomeworkCatalog_RequiredStrings", "length(\"HomeworkId\") > 0 AND length(\"Name\") > 0 AND length(\"Url\") > 0");

                            t.HasCheckConstraint("CK_HomeworkCatalog_TaskAndOrder", "\"TaskNumber\" BETWEEN 1 AND 1000 AND \"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("TestingHosting.Platform.Homework.HomeworkImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssignmentCreatedCount")
                        .HasColumnType("integer");

                    b.Property<int>("AssignmentRowCount")
                        .HasColumnType("integer");

                    b.Property<int>("AssignmentUnchangedCount")
                        .HasColumnType("integer");

                    b.Property<int>("CatalogCreatedCount")
                        .HasColumnType("integer");

                    b.Property<int>("CatalogRowCount")
                        .HasColumnType("integer");

                    b.Property<int>("CatalogUnchangedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProgramMapDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SubmissionCreatedCount")
                        .HasColumnType("integer");

                    b.Property<int>("SubmissionRowCount")
                        .HasColumnType("integer");

                    b.Property<int>("SubmissionUnchangedCount")
                        .HasColumnType("integer");

                    b.Property<string>("WorkbookDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Source", "WorkbookDigest", "ProgramMapDigest")
                        .IsUnique()
                        .HasDatabaseName("IX_HomeworkImportBatches_Digests");

                    b.ToTable("HomeworkImportBatches", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_HomeworkImportBatches_Counts", "\"CatalogRowCount\" >= 0 AND \"AssignmentRowCount\" >= 0 AND \"SubmissionRowCount\" >= 0 AND \"CatalogCreatedCount\" >= 0 AND \"CatalogUnchangedCount\" >= 0 AND \"CatalogCreatedCount\" + \"CatalogUnchangedCount\" = \"CatalogRowCount\" AND \"AssignmentCreatedCount\" >= 0 AND \"AssignmentUnchangedCount\" >= 0 AND \"AssignmentCreatedCount\" + \"AssignmentUnchangedCount\" = \"AssignmentRowCount\" AND \"SubmissionCreatedCount\" >= 0 AND \"SubmissionUnchangedCount\" >= 0 AND \"SubmissionCreatedCount\" + \"SubmissionUnchangedCount\" = \"SubmissionRowCount\"");

                            t.HasCheckConstraint("CK_HomeworkImportBatches_ProgramMapDigest_Length", "length(\"ProgramMapDigest\") = 64");

                            t.HasCheckConstraint("CK_HomeworkImportBatches_Status", "\"Status\" = 'applied'");

                            t.HasCheckConstraint("CK_HomeworkImportBatches_WorkbookDigest_Length", "length(\"WorkbookDigest\") = 64");
                        });
                });

            modelBuilder.Entity("TestingHosting.Platform.Homework.HomeworkSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsLate")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ScorePercent")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "EventId")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "ProgramId");

                    b.HasIndex("WorkspaceId", "AssignmentId", "CompletedAt");

                    b.HasIndex("WorkspaceId", "MembershipId", "StudentId");

                    b.HasIndex("WorkspaceId", "AssignmentId", "MembershipId", "StudentId", "ProgramId");

                    b.ToTable("HomeworkSubmissions", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_HomeworkSubmissions_RequiredStrings", "length(\"EventId\") > 0 AND length(\"SchemaVersion\") > 0");

                            t.HasCheckConstraint("CK_HomeworkSubmissions_ScoreDuration", "\"ScorePercent\" BETWEEN 0 AND 100 AND \"DurationSeconds\" BETWEEN 0 AND 86400");
                        });
                });

            modelBuilder.Entity("TestingHosting.Platform.IdentityAccess.TeacherUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("TeacherUsers", "platform");
                });

            modelBuilder.Entity("TestingHosting.Platform.IdentityAccess.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Workspaces", "platform");
                });

            modelBuilder.Entity("TestingHosting.Platform.IdentityAccess.WorkspaceMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TeacherUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherUserId");

                    b.HasIndex("WorkspaceId", "TeacherUserId")
                        .IsUnique();

                    b.ToTable("WorkspaceMemberships", "platform");
                });

            modelBuilder.Entity("TestingHosting.Platform.Persistence.StudentImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedStudentCount")
                        .HasColumnType("integer");

                    b.Property<string>("ProgramMapDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<int>("RowCount")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("UnchangedStudentCount")
                        .HasColumnType("integer");

                    b.Property<string>("WorkbookDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Source", "WorkbookDigest", "ProgramMapDigest")
                        .IsUnique();

                    b.ToTable("StudentImportBatches", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_StudentImportBatches_Counts", "\"RowCount\" >= 0 AND \"CreatedStudentCount\" >= 0 AND \"UnchangedStudentCount\" >= 0 AND \"CreatedStudentCount\" + \"UnchangedStudentCount\" = \"RowCount\"");

                            t.HasCheckConstraint("CK_StudentImportBatches_ProgramMapDigest_Length", "length(\"ProgramMapDigest\") = 64");

                            t.HasCheckConstraint("CK_StudentImportBatches_WorkbookDigest_Length", "length(\"WorkbookDigest\") = 64");
                        });
                });

            modelBuilder.Entity("TestingHosting.Platform.Students.LearningProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Code")
                        .IsUnique();

                    b.ToTable("Programs", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_Programs_Code_NotEmpty", "length(\"Code\") > 0");
                        });
                });

            modelBuilder.Entity("TestingHosting.Platform.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Students", "platform");
                });

            modelBuilder.Entity("TestingHosting.Platform.Students.WorkspaceStudentMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImportExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ImportSource")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("WorkspaceId", "Id", "StudentId", "ProgramId")
                        .HasName("AK_StudentMemberships_HomeworkIdentity");

                    b.HasIndex("StudentId");

                    b.HasIndex("WorkspaceId", "CodeHash")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "ProgramId");

                    b.HasIndex("WorkspaceId", "StudentId")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "ImportSource", "ImportExternalId")
                        .IsUnique()
                        .HasFilter("\"ImportSource\" IS NOT NULL AND \"ImportExternalId\" IS NOT NULL");

                    b.ToTable("WorkspaceStudentMemberships", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_WorkspaceStudentMemberships_CodeHash_Length", "octet_length(\"CodeHash\") = 32");

                            t.HasCheckConstraint("CK_WorkspaceStudentMemberships_ImportIdentity", "(\"ImportSource\" IS NULL) = (\"ImportExternalId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("TestingHosting.Platform.TestAttempts.TestAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Correct")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("MoscowMonthKey")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character(7)")
                        .IsFixedLength();

                    b.Property<int>("Percent")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<int>("TaskNumber")
                        .HasColumnType("integer");

                    b.Property<string>("TestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "EventId")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "ProgramId");

                    b.HasIndex("WorkspaceId", "MembershipId", "StudentId");

                    b.HasIndex("WorkspaceId", "MembershipId", "TestId", "MoscowMonthKey", "Percent", "DurationSeconds", "CompletedAt", "Id")
                        .IsDescending(false, false, false, false, true, false, false, false)
                        .HasDatabaseName("IX_TestAttempts_MonthlyBest");

                    b.ToTable("TestAttempts", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_TestAttempts_CountsAndPercent", "\"TaskNumber\" BETWEEN 1 AND 1000 AND \"Total\" BETWEEN 1 AND 10000 AND \"Correct\" BETWEEN 0 AND \"Total\" AND \"Percent\" = (\"Correct\" * 100 / \"Total\")");

                            t.HasCheckConstraint("CK_TestAttempts_MoscowMonthKey", "\"MoscowMonthKey\" ~ '^[0-9]{4}-(0[1-9]|1[0-2])$' AND \"MoscowMonthKey\" = (lpad(extract(year from (\"CompletedAt\" AT TIME ZONE 'Europe/Moscow'))::integer::text, 4, '0') || '-' || lpad(extract(month from (\"CompletedAt\" AT TIME ZONE 'Europe/Moscow'))::integer::text, 2, '0'))");

                            t.HasCheckConstraint("CK_TestAttempts_RequiredStrings", "length(\"EventId\") > 0 AND length(\"TestId\") > 0 AND length(\"Topic\") > 0 AND length(\"SchemaVersion\") > 0");

                            t.HasCheckConstraint("CK_TestAttempts_TimestampsAndDuration", "\"CompletedAt\" >= \"StartedAt\" AND \"DurationSeconds\" BETWEEN 0 AND 86400 AND \"CompletedAt\" - \"StartedAt\" <= interval '1 day' AND \"DurationSeconds\" = round(extract(epoch from (\"CompletedAt\" - \"StartedAt\")))::integer");
                        });
                });

            modelBuilder.Entity("TestingHosting.Platform.Homework.HomeworkAssignment", b =>
                {
                    b.HasOne("TestingHosting.Platform.IdentityAccess.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestingHosting.Platform.Students.LearningProgram", "Program")
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ProgramId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestingHosting.Platform.Homework.HomeworkCatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CatalogItemId", "ProgramId", "HomeworkId")
                        .HasPrincipalKey("WorkspaceId", "Id", "ProgramId", "HomeworkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_HomeworkAssignments_CatalogIdentity");

                    b.HasOne("TestingHosting.Platform.Students.WorkspaceStudentMembership", "Membership")
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "MembershipId", "StudentId", "ProgramId")
                        .HasPrincipalKey("WorkspaceId", "Id", "StudentId", "ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HomeworkAssignments_MembershipIdentity");

                    b.Navigation("CatalogItem");

                    b.Navigation("Membership");

                    b.Navigation("Program");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TestingHosting.Platform.Homework.HomeworkCatalogItem", b =>
                {
                    b.HasOne("TestingHosting.Platform.IdentityAccess.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestingHosting.Platform.Students.LearningProgram", "Program")
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ProgramId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TestingHosting.Platform.Homework.HomeworkImportBatch", b =>
                {
                    b.HasOne("TestingHosting.Platform.IdentityAccess.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TestingHosting.Platform.Homework.HomeworkSubmission", b =>
                {
                    b.HasOne("TestingHosting.Platform.IdentityAccess.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestingHosting.Platform.Students.LearningProgram", "Program")
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ProgramId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestingHosting.Platform.Students.WorkspaceStudentMembership", "Membership")
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "MembershipId", "StudentId")
                        .HasPrincipalKey("WorkspaceId", "Id", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestingHosting.Platform.Homework.HomeworkAssignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "AssignmentId", "MembershipId", "StudentId", "ProgramId")
                        .HasPrincipalKey("WorkspaceId", "Id", "MembershipId", "StudentId", "ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HomeworkSubmissions_AssignmentIdentity");

                    b.Navigation("Assignment");

                    b.Navigation("Membership");

                    b.Navigation("Program");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TestingHosting.Platform.IdentityAccess.WorkspaceMembership", b =>
                {
                    b.HasOne("TestingHosting.Platform.IdentityAccess.TeacherUser", "TeacherUser")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("TeacherUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingHosting.Platform.IdentityAccess.Workspace", "Workspace")
                        .WithMany("TeacherMemberships")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeacherUser");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TestingHosting.Platform.Persistence.StudentImportBatch", b =>
                {
                    b.HasOne("TestingHosting.Platform.IdentityAccess.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TestingHosting.Platform.Students.LearningProgram", b =>
                {
                    b.HasOne("TestingHosting.Platform.IdentityAccess.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TestingHosting.Platform.Students.WorkspaceStudentMembership", b =>
                {
                    b.HasOne("TestingHosting.Platform.Students.Student", "Student")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingHosting.Platform.IdentityAccess.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingHosting.Platform.Students.LearningProgram", "Program")
                        .WithMany("StudentMemberships")
                        .HasForeignKey("WorkspaceId", "ProgramId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("Student");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TestingHosting.Platform.TestAttempts.TestAttempt", b =>
                {
                    b.HasOne("TestingHosting.Platform.IdentityAccess.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestingHosting.Platform.Students.LearningProgram", "Program")
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ProgramId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestingHosting.Platform.Students.WorkspaceStudentMembership", "Membership")
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "MembershipId", "StudentId")
                        .HasPrincipalKey("WorkspaceId", "Id", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Membership");

                    b.Navigation("Program");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TestingHosting.Platform.IdentityAccess.TeacherUser", b =>
                {
                    b.Navigation("WorkspaceMemberships");
                });

            modelBuilder.Entity("TestingHosting.Platform.IdentityAccess.Workspace", b =>
                {
                    b.Navigation("TeacherMemberships");
                });

            modelBuilder.Entity("TestingHosting.Platform.Students.LearningProgram", b =>
                {
                    b.Navigation("StudentMemberships");
                });

            modelBuilder.Entity("TestingHosting.Platform.Students.Student", b =>
                {
                    b.Navigation("WorkspaceMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
